import type { OsuMapCategory } from "@/types";

export const MAPS_CATEGORIES: Record<OsuMapCategory, string> = {
  nm1: "NM1 (Raw Aim)",
  nm2: "NM2 (Flow Tapping)",
  nm3: "NM3 (Alternate)",
  nm4: "NM4 (Technical)",
  nm5: "NM5 (Finger Control)",
  nm6: "NM6 (Reading)",
  nm7: "NM7 (Polyrhythm)",
  hd1: "HD1 (Consistency)",
  hd2: "HD2 (Low AR)",
  hd3: "HD3 (Technical)",
  hr1: "HR1 (Consistency)",
  hr2: "HR2 (High CS)",
  hr3: "HR3 (Technical)",
  dt1: "DT1 (Consistency)",
  dt2: "DT2 (High BPM)",
  dt3: "DT3 (Technical)",
  dt4: "DT4 (Old Mapping)",
  fm1: "FM1 (Consistency)",
  fm2: "FM2 (Antimod)",
  fm3: "FM3 (Technical)",
  tb: "TB (Long Consistency)",
};

export const CATEGORIES_SORT_PRIORITIES = {
  nm1: 1,
  nm2: 2,
  nm3: 3,
  nm4: 4,
  nm5: 5,
  nm6: 6,
  nm7: 7,
  hd1: 8,
  hd2: 9,
  hd3: 10,
  hr1: 11,
  hr2: 12,
  hr3: 13,
  dt1: 14,
  dt2: 15,
  dt3: 16,
  dt4: 17,
  fm1: 18,
  fm2: 19,
  fm3: 20,
  tb: 21,
};
