import { OsuMapCategory } from "@/types/osumaps";
import { BotmClub } from "@/types/clubs";

export const SHIST_UID = "mjFMxVxnVrdAuYf0wYHY7Zb3KRl2";

export const MAPS_CATEGORIES: Record<OsuMapCategory, string> = {
  [OsuMapCategory.NM1]: "NM1 (Raw Aim)",
  [OsuMapCategory.NM2]: "NM2 (Flow Tapping)",
  [OsuMapCategory.NM3]: "NM3 (Alternate)",
  [OsuMapCategory.NM4]: "NM4 (Technical)",
  [OsuMapCategory.NM5]: "NM5 (Finger Control)",
  [OsuMapCategory.NM6]: "NM6 (Reading)",
  [OsuMapCategory.NM7]: "NM7 (Polyrhythm)",
  [OsuMapCategory.HD1]: "HD1 (Consistency)",
  [OsuMapCategory.HD2]: "HD2 (Low AR)",
  [OsuMapCategory.HD3]: "HD3 (Technical)",
  [OsuMapCategory.HR1]: "HR1 (Consistency)",
  [OsuMapCategory.HR2]: "HR2 (High CS)",
  [OsuMapCategory.HR3]: "HR3 (Technical)",
  [OsuMapCategory.DT1]: "DT1 (Consistency)",
  [OsuMapCategory.DT2]: "DT2 (High BPM)",
  [OsuMapCategory.DT3]: "DT3 (Technical)",
  [OsuMapCategory.DT4]: "DT4 (Old Mapping)",
  [OsuMapCategory.FM1]: "FM1 (Consistency)",
  [OsuMapCategory.FM2]: "FM2 (Antimod)",
  [OsuMapCategory.FM3]: "FM3 (Technical)",
  [OsuMapCategory.TB]: "TB (Long Consistency)",
};

export const CATEGORIES_SORT_PRIORITIES: Record<OsuMapCategory, number> = {
  [OsuMapCategory.NM1]: 1,
  [OsuMapCategory.NM2]: 2,
  [OsuMapCategory.NM3]: 3,
  [OsuMapCategory.NM4]: 4,
  [OsuMapCategory.NM5]: 5,
  [OsuMapCategory.NM6]: 6,
  [OsuMapCategory.NM7]: 7,
  [OsuMapCategory.HD1]: 8,
  [OsuMapCategory.HD2]: 9,
  [OsuMapCategory.HD3]: 10,
  [OsuMapCategory.HR1]: 11,
  [OsuMapCategory.HR2]: 12,
  [OsuMapCategory.HR3]: 13,
  [OsuMapCategory.DT1]: 14,
  [OsuMapCategory.DT2]: 15,
  [OsuMapCategory.DT3]: 16,
  [OsuMapCategory.DT4]: 17,
  [OsuMapCategory.FM1]: 18,
  [OsuMapCategory.FM2]: 19,
  [OsuMapCategory.FM3]: 20,
  [OsuMapCategory.TB]: 21,
};

export const CATEGORIES_COLORS = {
  [OsuMapCategory.NM1]: "#64b5f6",
  [OsuMapCategory.NM2]: "#42a5f5",
  [OsuMapCategory.NM3]: "#2196f3",
  [OsuMapCategory.NM4]: "#1976d2",
  [OsuMapCategory.NM5]: "#1565c0",
  [OsuMapCategory.NM6]: "#0d47a1",
  [OsuMapCategory.NM7]: "#003366",
  [OsuMapCategory.HD1]: "#ffd600",
  [OsuMapCategory.HD2]: "#f9a825",
  [OsuMapCategory.HD3]: "#c66900",
  [OsuMapCategory.HR1]: "#f0baba",
  [OsuMapCategory.HR2]: "#e57373",
  [OsuMapCategory.HR3]: "#c62828",
  [OsuMapCategory.DT1]: "#cda6d5",
  [OsuMapCategory.DT2]: "#ba68c8",
  [OsuMapCategory.DT3]: "#7e57c2",
  [OsuMapCategory.DT4]: "#5b259d",
  [OsuMapCategory.FM1]: "#94c596",
  [OsuMapCategory.FM2]: "#55aa59",
  [OsuMapCategory.FM3]: "#277d2b",
  [OsuMapCategory.TB]: "#d4ac7c",
};

export const CLUBS_INFO = [
  { id: BotmClub.AIM, title: "Aim Club" },
  { id: BotmClub.SPEED, title: "Speed Club" },
  { id: BotmClub.TECH, title: "Tech Club" },
  { id: BotmClub.READING, title: "Reading Club" },
  { id: BotmClub.HIDDEN, title: "Hidden Club" },
  { id: BotmClub.HARDROCK, title: "Hardrock Club" },
];
